services:
  db:
    build: db

  words:
    build: words
    depends_on:
      - db

  web:
    build: web
    volumes:
      - ./web/static:/static
    depends_on:
      - words
    ports:
      - "${WEB_PORT:-8080}:80"
